title: 'Turner Steakhouse'
desc: 'A1 vs Worchester'
code: 'turnersteakhouse'
preview_image: '/designs/turnersteakhouse/preview.png'
layout: multiple
is_public: true
default_logo: http://placehold.it/400x200
page_templates:
    - custom1:
        - image: { code: custom1_image, desc: 'Banner Image', hint: '' }
        - text: { code: custom1_content1, desc: 'Content Area 1', hint: '' }
        - text: { code: custom1_content2, desc: 'Content Area 2', hint: '' }
    - custom2:
        - image: { code: custom2_image1, desc: 'Banner Image Left', hint: '' }
        - image: { code: custom2_image2, desc: 'Banner Image Right', hint: '' }
        - text: { code: custom2_content1, desc: 'Content Area 1', hint: '' }
        - text: { code: custom2_content2, desc: 'Content Area 2', hint: '' }
    - custom3:
        - image: { code: custom3_image, desc: 'Banner Image', hint: ''}
        - text: { code: custom3_content_left, desc: 'Content Area 1 (text left)', hint: '' }
        - image: { code: custom3_image_right, desc: 'Content Area 1 (image right)', hint: '' }
        - text: { code: custom3_content2, desc: 'Content Area 2', hint: '' }
    - custom4:
        - text: { code: custom4_left_content1, desc: 'Left Column Content Area 1', hint: '' }
        - text: { code: custom4_left_content2, desc: 'Left Column Content Area 2', hint: '' }
        - image: { code: custom4_right_image, desc: 'Right Column Image', hint: '' }
        - text: { code: custom4_right_content1, desc: 'Right Column Content Area 1', hint: '' }
    - custom5:
        - image: { code: custom5_image, desc: 'Banner Image', hint: '' }
        - text: { code: custom5_content, desc: 'Content Area', hint: ''}
    - custom6:
        - text: { code: custom6_content1, desc: 'Content Area 1', hint: '' }
        - image: { code: custom6_image, desc: 'Sandwiched Image', hint: '' }
        - text: { code: custom6_content2, desc: 'Content Area 2', hint: '' }
    - custom7:
        - text: { code: custom7_content1, desc: 'Content Area 1', hint: '' }
        - image: { code: custom7_image_left, desc: 'Content Area 2 (image left)', hint: '' }
        - text: { code: custom7_content_left, desc: 'Content Area 2 (content right)', hint: '' }
        - text: { code: custom7_content_right, desc: 'Content Area 3', hint: '' }
    - custom8:
        - text: { code: custom8_content1, desc: 'Content Area 1', hint: '' }
        - text: { code: custom8_content2, desc: 'Content Area 2', hint: '' }
        - text: { code: custom8_content3, desc: 'Content Area 3', hint: ''}