title: 'Pizza'
desc: 'A Pizza design'
code: 'pizza'
preview_image: '/designs/pizza/preview.png'
layout: multiple 
is_public: true
default_logo: http://placehold.it/400x200
page_templates:
    - home:
        - text: { code: hours1, desc: "Your Hours Line 1", hint: '', editor: 'text'}
        - text: { code: hours2, desc: "Your Hours Line 2", hint: '', editor: 'text'}
        - text: { code: hours3, desc: "Your Hours Line 3", hint: '', editor: 'text'}
        - image: { code: home_banner, desc: "Banner Image", hint: 'Will be automaticly cropped to 1619x428', crop_width: '1619', crop-height: '428'}
        - text: { code: home_banner_text, desc: "Banner Text", hint: 'Try and keep text to no more than 3 lines'}
        - text: { code: home_content, desc: "Left Content", hint: '', editor_height: '120', editor: 'ckeditor'}
        - image: { code: pizza_home_menu_image_1, desc: 'Menu Image 1', has_caption: false, hint: '(Will be cropped to 171x107)', crop_width: '171', crop_height: '107' }
        - text: { code: pizza_home_menu_disc_1, desc: "Menu Text 1", editor: true, hint: 'Try and keep text to no more than 20 words'}
        - image: { code: pizza_home_menu_image_2, desc: 'Menu Image 2', has_caption: false, hint: '(Will be cropped to 171x107)', crop_width: '171', crop_height: '107' }
        - text: { code: pizza_home_menu_disc_2, desc: "Menu Text 2", editor: true, hint: 'Try and keep text to no more than 20 words'}
        - image: { code: pizza_home_menu_image_3, desc: 'Menu Image 3', has_caption: false, hint: '(Will be cropped to 171x107)', crop_width: '171', crop_height: '107' }
        - text: { code: pizza_home_menu_disc_3, desc: "Menu Text 3", editor: true, hint: 'Try and keep text to no more than 20 words'}
    - menu:
        - menu: { code: menu, desc: 'Menu', hint: '' }
        - image: { code: menu_header, desc: 'Header image', has_caption: false, hint: '' }
        - image: { code: menupdf, desc: 'Menu PDF', has_caption: false, hint: '' }
    - about:
        - text: { code: custom4_left_content1, desc: 'Left Column Content', hint: '', editor_height: '120', editor: 'ckeditor' }
        - image: { code: custom4_right_image, has_caption: false, desc: 'Right Column Image', hint: 'Image will be resized to fit 540px wide', crop_width: 540 }
    - events:
        - event: { code: event, desc: 'Event', hint: '' }
        - image: { code: events_header, desc: 'Header image', has_caption: false, hint: '' }
        - text: { code: event_text, desc: 'Event content', hint: '', editor_height: '120', editor: 'ckeditor' }
    - catering:
        - image: { code: catering_image, has_caption: false, desc: 'Top Image', hint: 'Image will be cropped and resized to fit 1200px wide by 480px high', crop_height: 480, crop_width: 1200 }
        - text: { code: catering_text, desc: 'Content', hint: '', editor_height: '120', editor: 'ckeditor' }
    - custom1:
        - image: { code: custom1_image, has_caption: false, desc: 'Top Image', hint: 'Image will be cropped and resized to fit 1200px wide by 480px high', crop_height: 480, crop_width: 1200 }
        - text: { code: custom1_content1, desc: 'Main Content', hint: '', editor_height: 120, editor: 'ckeditor' }
    - custom2:
        - image: { code: custom2_image1, has_caption: false, desc: 'Top Left Image', hint: 'Image will be cropped and resized to fit 480px by 480px', crop_height: 480, crop_width: 480 }
        - image: { code: custom2_image2, has_caption: false, desc: 'Top Right Image', hint: 'Image will be cropped and resized to fit 480px by 480px', crop_height: 480, crop_width: 480 }
        - text: { code: custom2_content1, desc: 'Main Content', hint: '', editor_height: 120, editor: 'ckeditor' }
    - custom3:
        - image: { code: custom3_image, has_caption: false, desc: 'Top Image', hint: 'Image will be cropped and resized to fit 1200px wide by 480px high', crop_height: 480, crop_width: 1200 }
        - image: { code: custom3_image_right, has_caption: false, desc: 'Right hand Image', hint: 'Image will be cropped and resized to fit 480px wide by 480px high and will float to the right of the content below', crop_width: 480, crop_height: 480 }
        - text: { code: custom3_content, desc: 'Main Content', hint: '', editor_height: 120, editor: 'ckeditor' }
    - custom4:
        - text: { code: custom4_left_content1, desc: 'Left Column Content', hint: '', editor_height: 120, editor: 'ckeditor' }
        - image: { code: custom4_right_image, has_caption: false, desc: 'Right Column Image', hint: 'Image will be resized to fit 540px wide', crop_width: 540 }
        - text: { code: custom4_right_content1, desc: 'Right Column Content', hint: '', editor_height: 120, editor: 'ckeditor' }
    - custom5:
        - text: { code: custom5_content1, desc: 'Top Content', hint: 'Displayed above image', editor_height: 120, editor: 'ckeditor' }
        - image: { code: custom5_image, has_caption: false, desc: 'Middle Image', hint: 'Image will be cropped and resized to fit 1200px wide by 480px high', crop_height: 480, crop_width: 1200 }
        - text: { code: custom5_content2, desc: 'Bottom Content', hint: 'Displayed below image', editor_height: 120, editor: 'ckeditor' }
    - custom6:
        - text: { code: custom6_content1, desc: 'Top Content', hint: '', editor_height: 120, editor: 'ckeditor' }
        - image: { code: custom6_image_left, has_caption: false, desc: 'Left Column Image', hint: 'Image will be resized to fit 540px wide', crop_width: 540 }
        - text: { code: custom6_content_left, desc: 'Left Column Content', hint: '', editor_height: 120, editor: 'ckeditor' }
        - text: { code: custom6_content_right, desc: 'Right Column Content', hint: '', editor_height: 120, editor: 'ckeditor' }
    - custom7:
        - text: { code: custom7_content, desc: 'Main Content', hint: '', editor_height: 160, editor: 'ckeditor' }
